### ISSUE TITLE
Modals broken

### ISSUE THREAD

**Issue by acirasa** [mrholek/CoreUI-React#12]
I try the demo in my workstation and all  working fine except for Modals.

if I click buttons the application freeze and nothing happen.

In console i read this message:

> Warning: Unknown props `onExited`, `appear`, `enter`, `exit` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Fade)
    in Fade
    in div (created by TransitionGroup)
    in TransitionGroup

There is something I missed in project setup or some dependency changed?

Thank you in advance

**Comment by xidedix** [comment]
downgrading react-transition-group to 1.2.0 seems to fix the issue for `reactstrap:v4.8.0` 
see: https://github.com/reactstrap/reactstrap/issues/502
moving to `reactstrap:v5` should solve the problem (when ready)

**Comment by acirasa** [comment]
Downgrading to 1.20  resolve this issue.
This fix solve FontAwesome problem too.

Thank you
Best Regards

**Comment by mrholek** [comment]
Fixed in latest version
