### ISSUE TITLE
FontAwesome

### ISSUE THREAD

**Issue by acirasa** [mrholek/CoreUI-React#13]
Hello,
There are some problems on FontAwesome.

When click on :

**SideMenu: Icons->FontAwesome** 

nothing happen and content area of application freeze.

I have missed something?

thank you in advance

**Comment by xidedix** [comment]
try move back react-transition-group to version : "^1.2.0" 
looks like it's related to #12 
reactstrap's v:4.8 modals and alerts are affected by this issue

**Comment by mrholek** [comment]
Fixed in latest version
