### ISSUE TITLE
'#' in uri

### ISSUE THREAD

**Issue by fajarkarim** [mrholek/CoreUI-React#26]
Thanks for very nice template here. I just wondering why in url have '#'  after base uri? is it can be remove ?

**Comment by fajarkarim** [comment]
solved , it's because i use hash router rather than browser router

**Comment by kahovn** [comment]
How to sold

**Comment by pjrola** [comment]
`import { **BrowserRouter**, Route, Switch } from 'react-router-dom';`

then use it in app.js

```
<BrowserRouter>
          <Switch>
            <Route exact path="/login" name="Login Page" component={Login} />
            <Route exact path="/register" name="Register Page" component={Register} />
            <Route exact path="/404" name="Page 404" component={Page404} />
            <Route exact path="/500" name="Page 500" component={Page500} />
            <Route path="/" name="Home" component={DefaultLayout} />
          </Switch>
</BrowserRouter>
```

**Comment by saeidabr60** [comment]
> `import { BrowserRouter, Route, Switch } from 'react-router-dom';`
> 
> then use it in app.js
> 
> ```
> <BrowserRouter>
>           <Switch>
>             <Route exact path="/login" name="Login Page" component={Login} />
>             <Route exact path="/register" name="Register Page" component={Register} />
>             <Route exact path="/404" name="Page 404" component={Page404} />
>             <Route exact path="/500" name="Page 500" component={Page500} />
>             <Route path="/" name="Home" component={DefaultLayout} />
>           </Switch>
> </BrowserRouter>
> ```

I've changed routing to this but after build I get this "..../Test%20Goes%20Here/../UI/build/index.html"
on URL and app didn't run.
