### ISSUE TITLE
Missing dependencies/modules 

### ISSUE THREAD

**Issue by kelson42** [mrholek/CoreUI-React#30]
I tried to run the `React_Full_Project` and achieved it but I had to install the following modules manually on the top of the one listed in `package.json`:
* `classnames`
* `prop-types`
* `node-sass`

**Comment by xidedix** [comment]
Hi @kelson42, thanks for reporting the issue!
`classnames` and `prop-types` are dependencies of Reactstrap, 
looks like something went wrong with the first installation of node modules.

Could you start from the scratch and let us know about any errors during install?

**Comment by kelson42** [comment]
@xidedix Tried again from scratch on an other computer and everything went fine !?!
