### ISSUE TITLE
How often do you update standard pro version ?

### ISSUE THREAD

**Issue by CharlieMarket** [mrholek/CoreUI-React#35]
This is a question. I buyed standard pro license to support your good work.
I saw updates in the demos from your site. When I will receive an update ?

**Comment by xidedix** [comment]
Hi @CharlieMarket  
Thank you for your support! 
We are doing our best to release the pro version once a month at least (and hotfixes as soon as possible).

**Comment by naturom** [comment]
Hi may i ask how do I update to latest version or pro version from existing project? it doesn't seem to documented anywhere

**Comment by Siffre** [comment]
@xidedix hello， I buyed standard pro license to support your good work yesterday, but how to upgrade latest version ?? this version is not my want

**Comment by xidedix** [comment]
Hi @Siffre 
Thanks for the catch! That's a definitely confusing screenshot picture on gumroad, we'll fix this.
see also: [How To Enable Dark Theme](https://github.com/coreui/coreui-react/issues/33)
