### ISSUE TITLE
Labels in horizontal form is too high.

### ISSUE THREAD

**Issue by loudking** [mrholek/CoreUI-React#37]
They should be as aligned vertically as inline form labels.
![label-in-horizontal-form](https://user-images.githubusercontent.com/11624509/34242973-79e2bfd8-e659-11e7-84b8-400d9c1e6017.png)
![label-in-inline-form](https://user-images.githubusercontent.com/11624509/34242974-7a316bba-e659-11e7-8ac2-a6d6b95aae9b.png)

**Comment by loudking** [comment]
Problem could be solved by adding classname = 'col-form-label'

**Comment by xidedix** [comment]
Hi @loudking 
Answering your original question:

> Hi, I tried following code but it has no effect - text still align left.

````html
<Label htmlFor="location" className="text-right">Location</Label>
````

use `className="float-right"` instead
