### ISSUE TITLE
Table header align bottom with <i>?

### ISSUE THREAD

**Issue by loudking** [mrholek/CoreUI-React#38]
Hi, with following code:

```
        <Table striped hover>
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Customer </th>
                </tr>
            </thead>
        </Table>
```

table header looks good
![thead_normal](https://user-images.githubusercontent.com/11624509/34286888-9a189348-e71e-11e7-8c38-8adaf388c272.png)

But when `<i>` is added to `<th>` element:

        <Table striped hover>
            <thead>
                <tr>
                    <th>Location <i className="fa fa-sort fa-lg mt-4"></i></th>
                    <th>Customer <i className="fa fa-sort fa-lg mt-4"></i></th>
                </tr>
            </thead>
        </Table>

table header looks to start align bottom.

![thead_align_bottom](https://user-images.githubusercontent.com/11624509/34286906-b2d37768-e71e-11e7-9a3c-3cafb80cdba2.png)

Can you please confirm if this is expected behavior or a bug?

**Comment by xidedix** [comment]
hi @loudking 
Table header looks like bottom aligned, since `margin-top` of `<i>` is set to 4 
Why don't you remove `mt-4` class?

**Comment by loudking** [comment]
Yes, my bad - after removing 'mt-4' everything works perfectly.

![table-header-good](https://user-images.githubusercontent.com/11624509/34318494-f619dbee-e803-11e7-9fd9-c46c1338e0d4.png)
