### ISSUE TITLE
Requesting for Form validation in CoreUI-React

### ISSUE THREAD

**Issue by Codeura-group** [mrholek/CoreUI-React#39]
Hello

I just purchase the CoreUI PRO and looking for form validation. They are available in other package (Vue JS and Jquery) but I don't see them in React. Would you please support for form validation in  React version of CoreUI?

**Comment by KevinGorjan** [comment]
Suggestion: redux-form.com?

Has everything you need ;-)

**Comment by Codeura-group** [comment]
I found it, thank you!

**Comment by nidhinchandran-mab** [comment]
@Codeura-group where did you find it ?
