### ISSUE TITLE
'webpack-dev-server' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by shubh4git** [mrholek/CoreUI-React#54]
coreui-react@1.0.0-alpha.6 start E:\Core Ui\CoreUI-Free-Bootstrap-Admin-Template\React_Full_Project
> webpack-dev-server --env.dev --open --hot --progress --colors --inline

'webpack-dev-server' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! coreui-react@1.0.0-alpha.6 start: `webpack-dev-server --env.dev --open --hot --progress --colors --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coreui-react@1.0.0-alpha.6 start script 'webpack-dev-server --env.dev --open --hot --progress --colors --inline'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the coreui-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --env.dev --open --hot --progress --colors --inline
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs coreui-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls coreui-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Core Ui\CoreUI-Free-Bootstrap-Admin-Template\React_Full_Project\npm-debug.log

**Comment by xidedix** [comment]
First of all, `CoreUI-React` has been moved to [https://github.com/mrholek/CoreUI-React](https://github.com/mrholek/CoreUI-React). Your version `coreui-react@1.0.0-alpha.6` is obsolete. Please use current version.

Assuming you've got `node` and `npm` installed, try:  
````bash
cd React_Full_Project
npm install
npm start
````

**Comment by xidedix** [comment]
I'm closing this since it appears to be answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by AbhishekNegi215** [comment]
DO 
npm install -g webpack-dev-server  
In your computer windows power shell
I hope this will Solve your Problem.
