### ISSUE TITLE
Problems with async/await integration 

### ISSUE THREAD

**Issue by zachgoll** [mrholek/CoreUI-React#57]
I am not all that experienced with webpack but have tried various methods to avoiding the 

`Uncaught ReferenceError: regeneratorRuntime is not defined`

when using async await syntax.  I tried several solutions such as [modifying webpack](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined) and using Facebook's `regenerator-runtime` package, but for whatever reason neither of them worked.

Can someone point me in the right direction to get this working please?

EDIT: I figured out the issue and wrote a quick post on how to solve it https://zachgoll.github.io/blog/2018/Async-Await-and-Regenerator-Runtime-Tutorial/

**Comment by Rsl1122** [comment]
Thank you for this write-up! Solved my issue. :)
