### ISSUE TITLE
Using it in combination with Electron

### ISSUE THREAD

**Issue by svanschooten** [mrholek/CoreUI-React#8]
We're trying to build an admin application using your ui kit (because its awesome), but we need it to integrate with [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate).
We have been working on this integration for about a whole week now, but still can't get it to work properly.

Could you help us?

**Comment by vincentvc** [comment]
Can you tell more what kinds of issue you are facing?

**Comment by mweiczorek** [comment]
I'm having similar issues. I tried generating CSS using the SASS compiler to import all the SCSS in your node_modules package, but I get this error:

Error: Invalid CSS after "...  50px !default": expected selector or at-rule, was "$navbar-brand-m..."
        on line 62 of ../../node_modules/@coreui/react/React_Full_Project/scss/core/_variables.scss
        from line 2 of ../../node_modules/@coreui/react/React_Full_Project/scss/core/core.scss
        from line 27 of ../../node_modules/@coreui/react/React_Full_Project/scss/style.scss
        from line 1 of core.scss

Unless I'm going about this the wrong way? I need the master CSS file in the main.js file of my Electron project, so it's part of the HTML document.

**Comment by xidedix** [comment]
Looks like you are trying to compile all scss files. 
Please try to start from `scss/style.scss`. It imports all other dependencies in the right order.

**Comment by AdnanBoota** [comment]
Hi,

I'm also trying to include into the  [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate), any ideas how can i integrate the admin template into this?

Any getting started for this integration?

**Comment by isalo** [comment]
did you find anything that you could share? I want to do the same integrate core-ui into electron app

**Comment by AdnanBoota** [comment]
Hi @isalo , no i haven't found any solution about integrating core-ui in electron, still looking for it, if you get any idea, please share here. thanks!

**Comment by isalo** [comment]
@AdnanBoota hi, i was able to make it work using 'resolve-url-loader', 'sass-loader'

**Comment by asad-amjad** [comment]
Hi, i am interating 'resolve-url-loader' and 'sass-loader' in [electron-react-boilerplate.](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

This error is coming.
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "v": expected 1 selector or at-rule, was 'var api = require("'

Have any idea about this error, Please tell
